#!/bin/bash
exec >nvidia-stop-stderrout.txt
exec 2>&1

echo "args: $@"
echo "hostname: `hostname`"

if [ -e nvidia-pids.txt ]; then
    while read pid; do
        kill -s SIGINT $pid
        wait $pid 2>/dev/null
    done <nvidia-pids.txt
    find . -name "nvidia-output.txt" -o -name "nvidia-collect-stderrout.txt" | while read line; do
	echo "Compressing: $line"
	xz -3 -T 0 $line
    done
else
    echo "Could not find nvidia-pids.txt"
    echo "PWD: `/bin/pwd`"
    echo "LS:"
    /bin/ls -l
    exit 1
fi
