#!/bin/bash
exec >nvidia-start-stderrout.txt
exec 2>&1

echo "args: $@"
echo "pwd: `/bin/pwd`"
echo "hostname: `hostname`"
# defaults
interval=10

longopts="interval:"
opts=$(getopt -q -o "" --longoptions "$longopts" -n "getopt.sh" -- "$@");
if [ $? -ne 0 ]; then
    printf -- "\tUnrecognized option specified\n\n"
    exit 1
fi
eval set -- "$opts";
while true; do
    case "$1" in
        --interval)
            shift;
            interval=$1
            echo "interval=$interval"
            shift;
            ;;
        --)
            shift;
            break
            ;;
        *)
            echo "Invalid option: $1"
            exit 1
    esac
done


/bin/rm -f nvidia-pids.txt
echo "Starting nvidia-collect.py"
TZ=UTC S_TIME_FORMAT=ISO nvidia-collect.py --interval $interval >nvidia-output.txt &
pid=$!
echo "$pid" >>nvidia-pids.txt
echo "nvidia pid is $pid"
